#!/bin/bash

set -e
export mailchk_workdir=$(cd $(dirname $0) && pwd)
. "$mailchk_workdir/common"

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
cPanel Mail Checker CLI
Version: $(cat $mailchk_workdir/VERSION)
https://github.com/TheGingeraffe/mail_checker/

Usage: $cli_name [command]

Commands:
  *              Help
  (d)ns          DNS Check
  (b)reakdown    Storage breakdown
  (f)ull         Run all options
"
  exit 1
}

# Logs/config here?

case "$1" in
  breakdown|b)
    "$mailchk_workdir/commands/breakdown"
    ;;
  dns|d)
    "$mailchk_workdir/commands/dns_check"
    ;;
  integrity|i)
    "$mailchk_workdir/commands/integrity"
    ;;
  perms|p)
    "$mailchk_workdir/commands/perms"
    ;;
  *)
    cli_help
    ;;
esac

# Pairs $address@$domain and pairs with domain in domain_info array
# TODO look in passwd, shadow, and maildir for addresses then compare
# TODO find a way to capture domain list from /var/cpanel/userdata/$(whoami)/main

for i in $(get_addresses); do
  address=${i%@*}
  domain=${i#*@}
  domain_info[$domain]+="$address "
done

