#!/bin/bash
# Breakdown

. "$mailchk_workdir/common"

if [[ ! -z "$2" ]]; then
  for domain in ${@:2}; do
    echo -e "\nUsage checks for ${domain}:\n"
    echo -e "Total:\n"
    get_size $domain
    echo -e "\nIndividual:\n"
    for address in ${domain_info["$domain"]}; do
    echo -e "${address}@${domain}\n"
    get_size $domain $address
    echo
    done
  done

else

echo
for domain in ${!domain_info[@]}; do
    echo -e "Usage checks for ${domain}:\n"
    echo -e "Total:\n"
    get_size $domain
    echo -e "\nIndividual:\n"
    for address in ${domain_info["$domain"]}; do
    echo -e "${address}@${domain}\n"
    get_size $domain $address
    echo
    done
  done

fi

# TODO mailbox breakdowns
# TODO mail counts
# TODO quotas
