#!/bin/bash

. "$mailchk_workdir/common"

# Iterates through domains and performs shadow/passwd file checks

if [[ ! -z "$2" ]]; then
  for domain in ${@:2}; do
    if [[ -e $HOME/etc/$domain/passwd ]] && \
    [[ -e $HOME/etc/$domain/shadow ]]; then
      hash_checker $domain shadow passwd
      hash_checker $domain passwd shadow
    else
      echo -e "\nThere is something wrong with the shadow/passwd files for ${domain}. \
Check that they exist and that permissions are correct.\n" \
      | fold -w 80 -s
    fi
  done
  if [[ "${#badaddresses[@]}" > 0 ]]; then
    echo -e "\nThese addresses may have issues. Check that \
the address exists in $HOME/mail/\$DOMAIN, has entries in \
$HOME/etc/\$DOMAIN/{shadow,passwd}, and that permissions are correct.\n" \
    | fold -w 80 -s
  for address in "${badaddresses[@]}"; do
    echo "$address"
  done 
  else
    echo -e "All addresses for domains on the account passed are found in the \
shadow/passwd files for \$DOMAIN and in $HOME/mail/\$DOMAIN."  
  fi

else

for domain in "${!domain_info[@]}"; do
  if [[ -e $HOME/etc/$domain/passwd ]] && \
  [[ -e $HOME/etc/$domain/shadow ]]; then
    hash_checker $domain shadow passwd
    hash_checker $domain passwd shadow
  else
    echo -e "\nThere is something wrong with the shadow/passwd files for ${domain}. \
Check that they exist and that permissions are correct.\n" \
    | fold -w 80 -s
  fi
done

if [[ "${#badaddresses[@]}" > 0 ]]; then
  echo -e "\nThese addresses may have issues. Check that\
 the address exists in $HOME/mail/\$DOMAIN, has entries in\
 $HOME/etc/\$DOMAIN/{shadow,passwd}, and that permissions are correct.\n" \
  | fold -w 80 -s
  for address in "${badaddresses[@]}"; do
    echo "$address"
  done
else
  echo -e "All addresses for domains on the account passed are found in the \
shadow/passwd files for \$DOMAIN and in $HOME/mail/\$DOMAIN."
fi
fi
echo

# TODO add uapi loop that recreates addresses if user says "yes" for each domain
# TODO eventually refactor for readability, make some vars etc.
