#!/bin/bash

. "$mailchk_workdir/common"

# Iterates through domains and performs shadow/passwd file checks

if [[ ! -z "$2" ]]; then
  for domain in ${@:2}; do
    if [[ -e $HOME/etc/$domain/passwd ]] && \
    [[ -e $HOME/etc/$domain/shadow ]]; then
      hash_checker $domain shadow passwd
      hash_checker $domain passwd shadow
    else
      echo -e "\nThere is something wrong with the shadow/passwd files for ${domain}. \
Check that they exist and that permissions are correct.\n" \
      | fold -w 80 -s
    fi
  done
  if [[ "${#badaddresses[@]}" > 0 ]]; then
    echo -e "\nThese addresses may have issues. Check that \
the address exists in $HOME/mail/\$DOMAIN, has entries in \
$HOME/etc/\$DOMAIN/{shadow,passwd}, and that permissions are correct.\n" \
    | fold -w 80 -s
    for domain in "${!badaddresses[@]}"; do
      for address in ${badaddresses["$domain"]}; do
        echo $address@$domain
      done
    done
  else
    echo -e "All addresses for domains on the account passed are found in the \
shadow/passwd files for \$DOMAIN and in $HOME/mail/\$DOMAIN."  
  fi

else

for domain in "${!domain_info[@]}"; do
  if [[ -e $HOME/etc/$domain/passwd ]] && \
  [[ -e $HOME/etc/$domain/shadow ]]; then
    hash_checker $domain shadow passwd
    hash_checker $domain passwd shadow
  else
    echo -e "\nThere is something wrong with the shadow/passwd files for ${domain}. \
Check that they exist and that permissions are correct.\n" \
    | fold -w 80 -s
  fi
done

if [[ "${#badaddresses[@]}" > 0 ]]; then
  echo -e "\nThese addresses may have issues. Check that\
 the address exists in $HOME/mail/\$DOMAIN, has entries in\
 $HOME/etc/\$DOMAIN/{shadow,passwd}, and that permissions are correct.\n" \
  | fold -w 80 -s
  for domain in "${!badaddresses[@]}"; do
      for address in ${badaddresses["$domain"]}; do
        echo $address@$domain
      done
    done
  echo
  answer=$(confirm "Would you like to attempt to repair these addresses? \
WARNING: This will reset the password for each repaired address.")
  while [[ $answer == "yes" ]]; do
    for domain in "${!badaddresses[@]}"; do
      cp -v $HOME/etc/$domain/{shadow,passwd}{,$(date +%s).bak}

    done
# TODO
    for address in "${badaddresses[@]}"; do
    echo -e "\nDoing stuff to ${address%@*}"
    if grep -q ${address%@*} $HOME/etc/${address#*@}/{shadow,passwd}; then
    echo "placeholder"
    fi
    #uapi Email add_pop \
    #email=${address%@*} \
    #password='echo $(cat /dev/urandom | tr -dc '[:upper:][:lower:][:digit:][:punct:]' | fold -w 12 | head -1)' \
    #quota=0 \
    #domain=${address#*@} \
    #skip_update_db=1
    done
  break
  done
else
  echo -e "All addresses for domains on the account passed are found in the \
shadow/passwd files for \$DOMAIN and in $HOME/mail/\$DOMAIN."
fi
fi
echo

# TODO add uapi loop that recreates addresses if user says "yes" for each domain
# TODO eventually refactor for readability, make some vars etc.
